---
title: "Performance 2021: Risultati"
author: "Controllo di Gestione e Performance"
date: '2022-02-23'
output: rtf_document
---

```{r include=FALSE}
library(tidyverse)
library(here)
library(flexdashboard)
library(knitr)
library(kableExtra)
library(formattable)
library(fmsb)
library(gt)
# library(patchwork)

perf <- readRDS("performance.RDS")
perf <-  perf %>%
    # mutate(Dipartimento = factor(Dipartimento, levels = c("Direzione Generale", 
    #                                                     "Direzione Sanitaria", 
    #                                                     "Direzione Amministrativa", 
    #                                                     "Dipartimento amministrativo", 
    #                                                     "Dipartimento tutela e salute animale", 
    #                                                     "Dipartimento sicurezza alimentare", 
    #                                                     "Dipartimento area territoriale Lombardia",
    #                                                     "Dipartimento area territoriale Emilia Romagna")), 
    #      Dipartimento = toupper(Dipartimento)) %>% 
  filter(Periodo == 4) %>%  
  mutate(Avanzamento = ifelse(Periodo == 4 & Avanzamento == 0, 1, Avanzamento) ) %>% 
  mutate(Avanzamento = ifelse(Avanzamento == 0.5, 1, Avanzamento)) 
```




# Introduzione


# Performance Strategica ( Livello Sintetico di Ente)

```{r echo=FALSE}
 gauge(100, min= 0, max = 100, symbol = '%',
           gaugeSectors(success = c(0,100),   colors = "steelblue"))
```




```{r echo=FALSE}
perf %>% 
  filter(Periodo == 4) %>% 
  group_by(MacroArea) %>% 
  summarise(media = 100*(mean(Avanzamento,na.rm  = T))) %>% 
  rename("Macro Area" = MacroArea,  " Performance ( media % di raggiungimento degli obiettivi delle corrispondenti Macro Aree)" = media) %>% 
  ungroup %>% 
  gt() %>% 
  fmt_number(columns = 2,decimals = 2)
```





# Perfromance Organizzativa

```{r echo=FALSE}
perf %>% 
  filter(Periodo == 4) %>% 
  group_by(MacroArea, Dipartimento) %>% 
  summarise(media = 100*mean(Avanzamento,na.rm  = T)) %>%
  ungroup() %>% 
  pivot_wider(names_from = Dipartimento, values_from = media) %>% 
  #replace_na(list(2:9)) %>% View()
  rename("Macro Area" = MacroArea) %>%
  gt() %>% 
  fmt_number(columns = 2:9,decimals = 2) %>% 
    fmt_missing(
    columns = 2:9,
    missing_text = "")
   
  

```



# Performance Individuale

# Monitoraggio

# Conclusioni


